name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.id || github.ref_name }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment:
      name: code_quality
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit
      - run: echo '${{ toJson(github.event) }}'
        continue-on-error: true
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Devenv
        uses: AlphaSphereDotAI/helpr_action/ci/setup/devenv@f94d2761e45aff60653b0cc344d1442127688983 # v0.0.13
      - name: Test
        run: devenv test
      - name: Commit pre-commit fixes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        if: success() || failure()
        with:
          commit_message: 'devenv: Apply Fixes'
          commit_options: --no-verify
  tag:
    name: Tag
    runs-on: ubuntu-latest
    environment: tagging
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    if: >-
      ${{ github.event_name == 'push' &&
          github.ref_type == 'branch' &&
          github.event.commits[0].author.name == 'renovate[bot]' &&
          contains(github.event.commits[0].message, 'chore(deps): update') }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit
      - run: echo '${{ toJson(github.event) }}'
        continue-on-error: true
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Setup Devenv
        uses: AlphaSphereDotAI/helpr_action/ci/setup/devenv@f94d2761e45aff60653b0cc344d1442127688983 # v0.0.13
      - name: Bump git version
        id: get_git_version
        if: ${{ ! contains(github.event.commits[0].message, 'alphaspheredotai/helpr_action') }}
        run: echo "result=$(devenv shell -q semver patch)" >> "$GITHUB_OUTPUT"
      - name: Update git tag
        if: ${{ contains(github.event.commits[0].message, 'alphaspheredotai/helpr_action') }}
        run: |
          GIT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null)
          git tag --force "$GIT_VERSION"
          git push origin --force HEAD:refs/tags/"$GIT_VERSION"
        shell: bash
      - name: Tag
        id: tag
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        if: steps.get_git_version.outcome == 'success'
        with:
          commit_message: 'Tag: ${{ steps.get_git_version.outputs.result }}'
          tagging_message: ${{ steps.get_git_version.outputs.result }}
          create_git_tag_only: true
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    if: >-
      ${{ github.event_name == 'push' &&
        github.ref_type == 'tag' }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          generate_release_notes: true
          make_latest: true
