name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.id || github.ref_name }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment:
      name: code_quality
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit
      - run: echo '${{ toJson(github.event) }}'
        continue-on-error: true
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Devenv
        uses: AlphaSphereDotAI/helpr_action/ci/setup/devenv@29475c7a807f8915f41785451d54f2e8b5c8f968 # v0.0.1
      - name: Test
        run: devenv test
      - name: Commit pre-commit fixes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        if: success() || failure()
        with:
          commit_message: 'devenv: Apply Fixes'
          commit_options: --no-verify
  tag:
    name: Tag
    runs-on: ubuntu-latest
    environment: tagging
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    if: >-
      ${{ github.event.commits[0].author.name == 'renovate[bot]' &&
          ! contains(github.event.commits[0].message, 'alphaspheredotai/helpr_action') &&
          contains(github.event.commits[0].message, 'chore(deps): update') &&
          github.event_name == 'push' &&
          github.ref_type == 'branch' }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit
      - run: echo "${{ toJson(github.event) }}"
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Devenv
        uses: AlphaSphereDotAI/helpr_action/ci/setup/devenv@29475c7a807f8915f41785451d54f2e8b5c8f968 # v0.0.1
      - name: Bump git version
        id: get_git_version
        run: echo "result=$(devenv shell -q semver patch)" >> "$GITHUB_OUTPUT"
      - name: Tag
        id: tag
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: 'Tag: ${{ steps.get_git_version.outputs.result }}'
          tagging_message: ${{ steps.get_git_version.outputs.result }}
  release:
    name: Release
    needs: tag
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    if: >-
      ${{
        github.event_name == 'push' &&
        github.ref_type == 'tag'
      }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          generate_release_notes: true
          make_latest: true
